#
# Docker-compose file for running the artifact evaluation
#
# Notes: 
#    The READMEs are put in ./workspace
#    The workspace will be owned by $USER_UID:$USER_GID
#

# Run as follows:
#
#    1) `cd` to the directory containing this file
#    2) Change USER_UID and USER_GID to the desired owner of your files (echo $UID )
#    3) Run the following command:
#
#        % docker-compose up
#
#    4) Look at output and use the 127.0.0.1 URL (unless you changed the port below)

# Notes (if URL does not work)
# Option1: uncomment the last line under `environment` to disable token and try again
# Option2: try the 192.168.X.X with the same token as shown in the output (X.X can be obtained by `hostname -I`)
# Option3: if you have access to docker GUI app (e.g., docker desktop), try locate the container ar the "containers" list and open the web page from there with the token (close and reopen the app if the container does not show up in the list)

version: '3'

services:
  micro-ae22:
    hostname: micro22-ae
    image: mitdlh/timeloop-accelergy-pytorch:micro22-artifact
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/home/workspace
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # - JUPYTER_SWITCHES=--NotebookApp.token=''
